apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ../../base/generic
  - ../../base/ambient-mode
  # - ../../base/sidecar-mode
patches:
  - path: patches/helm-release-istiod.yaml
