apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
resources:
  - ../../base
  # Custom Kyverno policies:
  # - ../../base/custom/my-custom-policy.yaml
patches:
  - path: patches/helm-release.yaml
