apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pinniped
resources:
  - ../../base
  - tlsroute-concierge.yaml
  - tlsroute-supervisor.yaml
  - supervisor-certificate.yaml
patches:
  - path: patches/helm-release.yaml
