apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
resources:
  - ../../base
  - static-key/static-key.yaml
patches:
  - path: patches/helm-release.yaml
  - path: patches/routes.yaml
