---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-client-credentials
  namespace: pinniped
spec:
  encryptedData:
    clientID: ""
    clientSecret: ""
  template:
    metadata:
      name: gitlab-client-credentials
      namespace: pinniped
    type: secrets.pinniped.dev/oidc-client
