apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
labels:
  - pairs:
      app.kubernetes.io/part-of: havenplus
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - namespace.yaml
