apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: jwt-authenticator
spec:
  issuer: "https://keycloak.havenplus-azure.haven.vng.cloud/realms/havenplus"
  audience: "pinniped-cli"
  claims:
    username: email
    groups: groups
