apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - cluster-resources.yaml
  - external-secrets.yaml
  - grafana.yaml
  - istio.yaml
  - kyverno.yaml
  - minio.yaml
  - nfs-server-provisioner.yaml
  - sealed-secrets.yaml
