# Either refer directly to a URL, or add the CRDs in this repo. 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # experimental-install required for now required for Gateway-API TLSRoute support
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml
  - https://download.elastic.co/downloads/eck/2.15.0/crds.yaml
  - ./network-policies
