apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - ../../base
  - schedules
  - s3-proxy
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: velero
      namespace: velero
