apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  name: keycloak
spec:
  issuer: https://keycloak.local/realms/master
  authorizationConfig:
    redirectURI: https://pinniped-supervisor.local/callback
    additionalScopes: [openid, email, profile]
  claims:
    username: preferred_username
    groups: groups
  client:
    secretName: keycloak-client-secret
