apiVersion: config.supervisor.pinniped.dev/v1alpha1
kind: FederationDomain
metadata:
  name: supervisor
spec:
  issuer: "https://pinniped-supervisor.havenplus-azure.haven.vng.cloud"
  tls:
    secretName: pinniped-supervisor-tls
