apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pinniped
resources:
  - ../../../base
  - clusterrolebinding.yaml
  - federation-domain.yaml
  - oidc-identity-provider.yaml
  - sealed-gitlab-client-credentials.yaml
patches:
  - path: patches/jwt-authenticator.yaml
