apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  name: gitlab
spec:
  issuer: https://gitlab.com
  authorizationConfig:
    additionalScopes: [openid,email]
  claims:
    username: email
    groups: groups
  client:
    secretName: gitlab-client-credentials
