---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-client-credentials
  namespace: pinniped
spec:
  encryptedData:
    clientID: AgAadDGsLH2NtkCjnFYQ4Vu498ByoUva+yoGGIR5PoUmHNpd2kkuFf6VgI9N3d9r2dseISLVUlQqHp7uD5pn4U+ld/cfI18Wi9wr3vKH3Co1+cgXPXROOJTpeDgy0r6jAaItC+gFZIKL38JV85a0lnUcMm6jsQOal7ipQ9/xMPd9vYumOlvI94pv0Ztg0JrcKpzATcddJk8j79OyMbRefrw82UKWJMUSa55QFIKqrmulMylSIBw4lTqR1NGfe8cbLrpz8MobNb906yCzSD2W7s+gP7F31UNo8JZUPLRStGc7UKHrxXLByDJQmcN383ER5khdk+c4TNKyQW1bmSPDa7cAUJkNJpqoXHmPZ8UF2l/N+PisYUHuOLQGVI1NeDwmeHX4yLDJP/DjWPnlYhYLuSR2IqDu1LrO6es1x4WUERf+R9g4mrN8F8w2ScQ8qRQ8vhJvHwobX6xvUxgO8s/PtMUJLyUFErjQaZwNB58ibrXwo+2P6nU9XXuMLwAp45s7iikrZZwLNxeoH6L5IbQUeNQwxAMyOUbxSpI6i5zftHxzhII8KeUV8EnOQ/IONX31B8DWm7bPC+l+PakoWVNxttyyYPmZ5rJep/3W3ShP5+OUjrHMyHDO4jjDXkc5Z4xpy4tscaEne0oPhCqnG+5gVf4ij7SRE2tFluP7yPva6odkDuLcYcHFi6XilHCpDBLq7NDEoVz8l3MFjSraxTdj/S5QVdXHmRAAFpBV8c4mzjXz7IvXqU1ykKa2I6FwIyvYFCWLPKAkB5Z+sWeyvPQRFNkW
    clientSecret: AgAKcTMvutVCcFOFfXKCXmfxMDl0IAk4Jv6EgWT5oE0H6Ebb83OEu7FNbk+XWpmNaSvZrz5cqVTCYVZoSmaWhf6Nci3GGfpVpHJ9WrNzlpGKzkcNHjQb/B3fRP3hTzlTn+LWT0v9axsx+ZSb+sF26rnrCmZLUPmrNY6+p51TG41lvsMYUNVptcZG3ra9wBSnNLxT1u+o0wxMDW+F6YvwSXAgPAruv4LSQxGj/8yq8nKTQVNbXlxldIM/qmrbe25fWApviuNaX+0O1xBGBfomkBlkI4gNw/DnP41N228FiKFelQjZrSk9AMYVIT0nt9n89Ct+jjIDwvw0Lq697y1pD0l9HFvCIvwr2p+9MrmIRJihs96hS5vpjyXywzxPm/On+0nSh6Qpsuu8v84FfzUfus4sJmZefDbUh/dH/lPXBIIw6djF5TcD3U0DVDj28YUrBDI47pX+2cZgD9BUZccVyTbfDyoVtj6QHM7BgI8dbOv8JMAXt00IqCO484h76z5xXig5H/5lNnM6rQ3FqXd2ZS2IMg9j/Tiy2qhUYIOiqqI6CgmrvKVD7kTg6Jrvp2qCXULFaenYeQx8vVkVYA3Z3k5cyLEaz+oxBpJHzRs9C+sgKM6+0rVmy0gCNEazSpKmO8Ln8BMI9id438A45pEfxQCSdPFZoZl8diQiKh0kPNTcYIkUyYIPhaz7xbNqL1arDq5FpaAk2fBn4Pg4m/1a6ND/atWRSzKey4OWoI9zCTkdQLA4IimgPCtMuW14koG+uo6drZnkVqbAtzl133JpPvp5J7h/2xbw
  template:
    metadata:
      name: gitlab-client-credentials
      namespace: pinniped
    type: secrets.pinniped.dev/oidc-client
