apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: flux
resources:
  - dashboards.yaml
  - grafana.yaml
  - loki-datasource.yaml
  - mimir-datasource.yaml
  - cnpg.yaml
  - namespaces.yaml