apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: mimir
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: mimir
    access: proxy
    type: prometheus
    url: http://mimir-monolithic.mimir.svc.cluster.local:8080/prometheus
    jsonData:
      "httpHeaderName1": "X-Scope-OrgId"
    secureJsonData:
      "httpHeaderValue1": "admin"