apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy.yaml
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - cluster-resources.yaml
  - eck-operator.yaml
  - external-secrets.yaml
  - falco.yaml
  - grafana.yaml
  - headlamp.yaml
  - istio.yaml
  - keycloak.yaml
  - kube-state-metrics.yaml
  - kyverno.yaml
  - loki.yaml
  - metallb.yaml
  - mimir.yaml
  - nfs-subdir-external-provisioner.yaml
  - opencost.yaml
  - pinniped.yaml
  - sealed-secrets.yaml
  - tempo.yaml
  - trivy-operator.yaml
  - velero.yaml
