apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pinniped
resources:
  - ../../base
  - federation-domain.yaml
  - keycloak-client-secret.yaml
  - oidc-identity-provider.yaml
patches:
  - path: patches/jwt-authenticator.yaml
