apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  name: keycloak
spec:
  issuer: https://<your-keycloak-domain>/realms/master
  authorizationConfig:
    redirectURI: https://<pinniped-supervisor-domain>/callback
  claims:
    username: preferred_username
    groups: groups
  client:
    secretName: keycloak-client-secret
