apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pinniped
resources:
  - ../../base
  - ingress-concierge.yaml
patches:
  - path: patches/helm-release.yaml
  - path: patches/supervisor-certificate.yaml
