apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak-instances
resources:
  - cnpg.yaml
  - httproute.yaml
  - keycloak.yaml
  - namespace.yaml
  - pinniped-client.yaml
  - sealed.yaml
