apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources: [] # remove [] and uncomment below once provider specific config has been added in the patch
#   - ../../base
# patches:
#   - path: patches/helmrelease.yaml
