apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: "<email_address>"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-private-key
    solvers:
      - dns01:
          azureDNS:
            hostedZoneName: "<hosted_zone_name>"
            resourceGroupName: "<resource_group_name>"
            subscriptionID: "<subscription_id>"
            environment: AzurePublicCloud
            managedIdentity:
              clientID: "<client_id>"
        selector:
          dnsZones:
            - "<dns_zone>"
