apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak-instances
resources:
  - ../../base
  - sealed.yaml
patches:
  - target:
      kind: Keycloak
      name: keycloak
    patch: |
      - op: replace
        path: /spec/hostname/hostname
        value: keycloak.local
  - target:
      kind: HTTPRoute
      name: keycloak
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: keycloak.local
