apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - ../../base
  - scc.yaml
patches:
  - path: ./patches/helm-release.yaml
    target:
      kind: HelmRelease
      name: ingress-nginx
