apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - azureblob-premium-lrs-nfs.yaml
  - azureblob-premium-zrs-nfs.yaml
  - azurefile-premium-lrs-nfs.yaml
  - azurefile-premium-zrs-nfs.yaml
