apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../base
  - sealed.yaml
patches:
  - path: patches/helm-release.yaml
  - path: patches/cnpg.yaml
  - path: patches/routes.yaml