apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sealed-secrets-public-key
spec:
  parentRefs:
  - name: "set-in-overlay"
    namespace: istio-ingress
  hostnames:
  - "set-in-overlay"
  rules:
    - filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /v1/cert.pem
      backendRefs:
        - name: sealed-secrets-controller
          port: 8080