apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy.yaml
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - cluster-resources.yaml
  - eck-operator.yaml
  - external-secrets.yaml
  - grafana.yaml
  - headlamp.yaml
  - istio.yaml
  - keycloak.yaml
  - loki.yaml
  - mimir.yaml
  - pinniped.yaml
  - sealed-secrets.yaml
  - tempo.yaml
