apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: jwt-authenticator
spec:
  issuer: "https://keycloak.local/realms/master"
  audience: "account"
  claims:
    username: preferred_username
    groups: groups
